services:
  controller:
    image: ngrinder/controller:3.5.9-p1
    ports:
      - "8088:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ngrinder_controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent:3.5.9-p1
    depends_on:
      - controller
    command: ["controller:80"]

volumes:
  ngrinder_controller:
